version: '3.7'

services:
    react:
        build: ./web
        container_name: react_colab
        ports:
            - "3000:3000"
        volumes:
            - ./web/:/usr/app
        stdin_open: true
        command: npm start

